hyprwm/hyprlock

- src/config/ConfigManager.cpp
- src/renderer/Renderer.cpp
- src/renderer/widgets/PasswordInputField.cpp
- src/renderer/widgets/PasswordInputField.hpp
I found intresting to be able to change the font color for it.
It was nice and easy thanks to Hyprlang!
> input-field: add font color config option

- nix/hm-module.nix
Fixes home manager module and adds some extra configs
> Fix Home Manager Module

- nix/hm-module.nix
sorry for the 2 other commits forgot to merge the last one Xd
cc: @fufexan
> nix: add color option to backgrounds in the hm module

- nix/hm-module.nix
cc: @fufexan 
(sorry for the PR spam, take your time if you're busy)
> nix: add package to home.packages in hm module

- nix/hm-module.nix
My first PR in an official project :o 
Forgot in the commit message: also added hide_cursor option
Hope I did everything correctly :)
cc: @fufexan
> Nix: add hide_input to hm module + correctly convert bools to strings

- src/core/hyprlock.cpp
Don't know if this is enough, but it works 😅
#19
> Clear password buffer with escape key

- nix/hm-module.nix
Convert the input fields and labels to type = listOf submodule to allow the creation of multiple labels / input fields
cc: @fufexan
> Nix: HM module: add dots options + convert input fields and labels to type = listOf submodule

- nix/hm-module.nix
Add dots_center to home-manager module.
> nix: add dots_center

- nix/hm-module.nix
@fufexan Just saw a commit added this option too
> nix: add general:grace

- src/config/ConfigManager.cpp
- src/config/ConfigManager.hpp
- src/helpers/MiscFunctions.cpp
- src/helpers/MiscFunctions.hpp
This allows for out**source**ing configs into other files. Fixes #15
> config: add source parsing

- README.md
https://github.com/hyprwm/hyprlock/commit/29c5d4da94a26ba6a6491c24de113ee9c0a2b29c
Should this be added in the README too?
and yeah, probably also in the aur pkgbuild
> add libdrm dependency in README

- src/core/hyprlock.cpp
Fix #16 .As title said this allow user to send SIGUSR1 to hyprlock process to unlock it.  hopefully it went well.
and sorry for my bad English
> Allow send SIGUSR1 to unlock

- src/renderer/widgets/PasswordInputField.cpp
- bring back fade
- animate overflow
https://github.com/hyprwm/hyprlock/assets/130279855/d1146760-a8fc-4b71-9ec4-318f0c125299
> input-field: dots improvements

- src/main.cpp
Add a -help arg option to solve #69
> core: add help message

- nix/hm-module.nix
- src/config/ConfigManager.cpp
- src/renderer/widgets/PasswordInputField.cpp
- src/renderer/widgets/PasswordInputField.hpp
Adds a rounding option to input field so you're not forced to have a pill shaped input field
> Add rounding option to input field

- nix/hm-module.nix
- src/config/ConfigManager.cpp
- src/renderer/widgets/PasswordInputField.cpp
- src/renderer/widgets/PasswordInputField.hpp
Follow-up 49ef1d306c92bbfef057272ae0bdefe8aea8d0c7
`-2` kinda follow input-field rounding
> input-field: add dots rounding option

- src/core/hyprlock.cpp
- src/core/hyprlock.hpp
- src/main.cpp
Fixes: https://github.com/hyprwm/hyprlock/issues/143
> core: add commandline switch to lock immediately

- nix/hm-module.nix
adds hm options for `shadow_passes`, `shadow_size`, `shadow_color` & `shadow_boost`
diff looks ugly cuz indentation changed, I just added `// shadow` to Background, Input Field & Label
> Nix/HM module: add shadow options

- src/core/hyprlock.cpp
For example when using systemd-homed with fido auth
> Handle slow pam verification

- src/renderer/widgets/PasswordInputField.cpp
- src/renderer/widgets/PasswordInputField.hpp
kindly supersedes #174, also not to break resizing on fail
thanks @PaideiaDilemma for pointing out :heart:
> input-field: fix alignment on multi-monitors

- src/core/hyprlock.cpp
- src/renderer/widgets/PasswordInputField.cpp
> core: fix libc++ compatibility

- src/config/ConfigManager.cpp
- src/config/ConfigManager.hpp
- src/main.cpp
just copy-pasted from hypridle
strange it's not here already
> config: add -c, --config commandline options

- src/core/hyprlock.cpp
- src/core/hyprlock.hpp
Fixes https://github.com/hyprwm/hyprlock/issues/222
> Make Ctrl+u clear password input

- nix/hm-module.nix
Fixes #231
@Anomalocaridid can you test whether this fixes your issue?
> Nix/HM module: add sources and extraConfig

- nix/hm-module.nix
> Nix/HM module: fix rotate options

- nix/hm-module.nix
Updating images to support shadow properties per docs: https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#image
> nix/hm-module: add shadowable to images

- src/core/hyprlock.cpp
Fix for releasing the session lock twice when `general:no_fade_out` and when unlocking via signal
> core: avoid double unlocks with no_fade_out

- src/core/LockSurface.cpp
> fix initialization issues in LockSurface

- src/config/ConfigManager.cpp
- src/renderer/AsyncResourceGatherer.cpp
ref. https://github.com/hyprwm/hyprlock/issues/284
Not sure if that's the best way to trim a string in C++, please let me know if there's a better solution.
If it will be accepted I'll update the wiki too.
> renderer: add text trim with option to disable

- src/renderer/AsyncResourceGatherer.cpp
> gatherer: use absolute path in magic guess

- src/main.cpp
> Inproved error handling and arg parsing

- src/core/LockSurface.cpp
Fixes some bugs in the LockSurface
- Surface Creation Check in Constructor: Replaced !surface check with !lockSurface to correctly handle creation failure
- Surface Destruction in Destructor: Added a check if (surface) before wl_surface_destroy(surface) 
- Verify that fractionalScale calculation is correct.
- Improved error handling around eglSurface creation.
- Proper synchronization and cleanup of frameCallback: Set needsFrame to false on Callback before calling render().
> "Some bug fixing"

- src/core/LockSurface.cpp
- src/renderer/AsyncResourceGatherer.cpp
- src/renderer/AsyncResourceGatherer.hpp
- src/renderer/Renderer.cpp
> core: handle missing wayland protocol support

- src/config/ConfigManager.cpp
- src/config/ConfigManager.hpp
- src/core/hyprlock.cpp
- src/core/hyprlock.hpp
- src/helpers/Box.cpp
- src/helpers/Box.hpp
- src/helpers/Jpeg.cpp
- src/helpers/Log.hpp
- src/helpers/MiscFunctions.hpp
- src/helpers/Vector2D.hpp
- src/main.cpp
- src/renderer/AsyncResourceGatherer.cpp
- src/renderer/AsyncResourceGatherer.hpp
- src/renderer/DMAFrame.cpp
- src/renderer/DMAFrame.hpp
- src/renderer/Framebuffer.cpp
- src/renderer/Renderer.cpp
- src/renderer/Renderer.hpp
- src/renderer/widgets/IWidget.cpp
- src/renderer/widgets/Label.cpp
- src/renderer/widgets/Label.hpp
- src/renderer/widgets/Shadowable.hpp
**Label**
- Added exception handling in label constructor
**Log**
- Used std::abort() to terminate the program instead of de-referencing null pointer.
**Frambuffer**
- Added check to ensure m_pStencilTex is valid before usage.
-  sets m_pStencilTex to nullptr after release.
**Misc**
- Headers
> Label exception handling + Frambuffer checks + headers

- .gitignore
- CMakeLists.txt
- flake.lock
- src/config/ConfigManager.cpp
- **flake.lock: update**
- **gitignore: add CMake residual files**
- **config: use hyprutils helper**
- **CMake: update required hyprutils version**
Untested.
> Config: use hyprutils helper

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
Copied from Hyprland and slightly modified.
I think this will reduce the amount of times we have to ask for versions of hyprlock and hyprland.
~_I don't know if it is enough to just merge this to set the templates..._~
> misc: add issue templates

- src/main.cpp
Totally not my fault
---
okay maybe a bit, sorry for having an iq of 60
> fix alignment in help message

- src/renderer/AsyncResourceGatherer.cpp
> fix symlinked images not picking up extension

- src/renderer/AsyncResourceGatherer.cpp
Caused by my last commit, sorry.
> asyncResourceGatherer: stop worker threads when application is going to exit

- src/renderer/widgets/IWidget.cpp
Closes https://github.com/hyprwm/hyprlock/issues/493.
>why would you want to use an inferior time format?
No idea, but seems that some users prefer it.
> widgets: add 12h time format

- src/renderer/widgets/PasswordInputField.cpp
fixes #528
Mistakes were made...
> input-field: fix invert_numlock regression

- src/renderer/widgets/IWidget.cpp
ups, I removed that but didn't seem to push it
> widgets: remove debug remnants from #527

- src/core/hyprlock.cpp
- src/core/hyprlock.hpp
> core: add support for composed keys

- src/renderer/widgets/PasswordInputField.cpp
> input-field: improve/fix behaviour of *lock colors

- src/renderer/widgets/Label.cpp
- src/renderer/widgets/Label.hpp
Closes https://github.com/hyprwm/hyprlock/issues/598
> label: fix redrawing shadow on label updates

- src/auth/Fingerprint.cpp
- src/auth/Fingerprint.hpp
- src/renderer/widgets/IWidget.cpp
Quick and crude fix targetted at the issue I raised in #608.
> Better feedback from fingerprint auth and don't clear password field on retry (only on failure)

- .gitignore
- CMakeLists.txt
- README.md
- flake.lock
- flake.nix
- nix/default.nix
- nix/overlays.nix
- src/core/CursorShape.cpp
- src/core/CursorShape.hpp
- src/core/Egl.hpp
- src/core/LockSurface.cpp
- src/core/LockSurface.hpp
- src/core/Output.cpp
- src/core/Output.hpp
- src/core/Seat.cpp
- src/core/Seat.hpp
- src/core/hyprlock.cpp
- src/core/hyprlock.hpp
- src/renderer/DMAFrame.cpp
- src/renderer/DMAFrame.hpp
- src/renderer/widgets/IWidget.cpp
@fufexan nix bump pls hw-s 0.4.4
@PaideiaDilemma can you run a test? :)
> Core: move to hyprwayland-scanner

- src/renderer/widgets/PasswordInputField.cpp
> input-field: don't change outer color when numlock_color is not set

- src/core/Seat.cpp
> Unbreak build on FreeBSD >= 13.4

- src/core/Output.cpp
> output: fix setting transform

- src/core/AnimationManager.cpp
Same as https://github.com/hyprwm/Hyprland/pull/9030
> animation: allow adding vars during ::tick

- src/core/AnimationManager.cpp
- src/renderer/widgets/PasswordInputField.cpp
> animation: small gradient fail transition fixup

- src/renderer/widgets/IWidget.cpp
> widgets: unbreak libc++ < 19 build

- src/auth/Fingerprint.cpp
Catch errors when setting up the dbus connection.
Related: https://github.com/hyprwm/hyprlock/issues/650
Donno if that's the problem, but this here is good to have in either way.
> fingerprint: handle failed dbus connection

- src/config/ConfigManager.cpp
- src/core/AnimationManager.cpp
- src/renderer/widgets/PasswordInputField.cpp
Closes https://github.com/hyprwm/hyprlock/issues/651
> animations: linear bezier for gradient, warp behavior

- src/config/ConfigManager.cpp
> config: make sure disabled animation don't need a valid speed or bezier

- src/renderer/widgets/Image.cpp
- src/renderer/widgets/Image.hpp
Closes https://github.com/hyprwm/hyprlock/issues/733
> image: remove a left over raw pointer to COutput

- src/config/ConfigManager.cpp
> config: default to center for label halign and valign

- CMakeLists.txt
- README.md
- nix/default.nix
- src/renderer/AsyncResourceGatherer.cpp
Remove some deps that are now required by hyprutils.
Cleanup feature and dependency lists in the README.
> misc: readme cleanup, remove deps required by hyprgraphics

- src/main.cpp
> core: disable fade in when using --immediate

- CMakeLists.txt
- flake.lock
- src/auth/Auth.cpp
- src/auth/Auth.hpp
- src/auth/Fingerprint.cpp
- src/core/Seat.cpp
- src/core/Timer.cpp
- src/core/Timer.hpp
- src/core/hyprlock.cpp
- src/core/hyprlock.hpp
- src/defines.hpp
- src/renderer/Renderer.cpp
- src/renderer/Renderer.hpp
- src/renderer/widgets/Background.cpp
- src/renderer/widgets/Background.hpp
- src/renderer/widgets/Image.cpp
- src/renderer/widgets/Image.hpp
- src/renderer/widgets/Label.cpp
- src/renderer/widgets/Label.hpp
- src/renderer/widgets/PasswordInputField.cpp
- src/renderer/widgets/PasswordInputField.hpp
- src/renderer/widgets/Shadowable.cpp
- src/renderer/widgets/Shadowable.hpp
- src/renderer/widgets/Shape.cpp
- src/renderer/widgets/Shape.hpp
Successor of #799
Closes https://github.com/hyprwm/hyprlock/issues/785
Requires https://github.com/hyprwm/hyprutils/pull/57 and a Hyprutils version increment.
> core: use hyprutils atomic pointers

- src/core/hyprlock.cpp
> core: limit onClick to down events
