hyprwm/hyprlock

src/renderer/widgets/IWidget.cpp
Before this change, system's time zone was not used to return the time
=> Use local time for $TIME variable

nix/hm-module.nix
changed cfg from config.services.hyprlock to config.programs.hyprlock
cc: @fufexan
=> nix: fix hm module

src/core/Output.cpp
Currently there is an issue with rotated setups
Added support for monitors rotated at 90/270 degrees to fix display issues with rotated setups.
=> Add support for 90/270 degree rotated monitors

src/core/LockSurface.cpp, src/core/LockSurface.hpp
Oopsies and stuff shoutout Simon Ser and ashaffer for help :)
hopefully fixes #9
=> Nvidia and stuff fixes

nix/hm-module.nix
This should bring the Home-Manager module up to date with the current configuration settings available.
=> Nix: add blur settings and no_fade_in

CMakeLists.txt, src/core/Password.cpp, src/core/hyprlock.cpp, src/renderer/DMAFrame.cpp, src/renderer/widgets/IWidget.cpp
Tested with GCC 13 on FreeBSD 14.0/13.2 amd64/i386. Runtime is blocked by #70 (system hyprlang package is built against libc++).
=> Unbreak build on FreeBSD

src/renderer/AsyncResourceGatherer.cpp, src/renderer/widgets/IWidget.cpp
Fixes #70. Tested with Clang/libc++ 17
- libc++ 18 has [atomic floats](https://github.com/llvm/llvm-project/commit/de7fbfeef598) but libc++ < 18 may still be common on distros
- libc++ 19 has [tzdb](https://github.com/llvm/llvm-project/commit/d332d88b919f) and [soon](https://github.com/llvm/llvm-project/pulls?q=is%3Apr+is%3Aopen+current_zone) will have `current_zone`
=> Unbreak build with libc++

src/config/ConfigManager.cpp
Fixes https://github.com/hyprwm/hyprlock/issues/73. Tested with Clang/libc++ 17 and 18
=> fix libc++ compatibility v2

src/renderer/widgets/PasswordInputField.cpp
=> renderer: restrict maximum dot amount w.r.t to input width

src/renderer/widgets/PasswordInputField.cpp
i think we can do this cause already checked with
```c
dots.currentAmount != PASSLEN
```
gpu not happy when `fade_on_empty = true`
=> render: remove alpha check for input-field

src/core/hyprlock.cpp
Switches from using sym values to the raw key value which solves #86
=> core: use raw key values for tracking keypresses

src/core/hyprlock.cpp, src/renderer/widgets/PasswordInputField.cpp
This makes it so that
1. The renderer is triggered when the onPasswordCheckTimer callback is fired. Previously you had to give an additional input for the renderer to be triggered and the fail reason to show.
2. The updateDots function now sets dots.currentAmout to 0, when a failID is present and PASSLEN is 0. That leads to the draw function to return false and the failReason to be displayed until another input happens.
Addresses #97
**Previous behavior (I pressed a key at the end)**
https://github.com/hyprwm/hyprlock/assets/78690852/df047d4b-7ab6-4fa9-9abb-b1844841821f
**Behavior introduced here** 
https://github.com/hyprwm/hyprlock/assets/78690852/b900be89-fe30-449b-a60f-441770c8490f
=> Show autentication failReason without additional input

src/core/hyprlock.cpp
Fix typo and ignore key up 
When you start hyprlock via a key press, then there is a stray key up event that would trigger the grace period unlock.
~This is also notable because without ignoring key up also ran into a racy bug that is probably the same as #107. So unlocking the screen quickly after startup seems to trigger it. Did not figure out what is going on yet tough.~ (That was because of locking a locked session)
Fixes #112
=> grace: ignore key up and fix typo

src/core/hyprlock.cpp
This reverts commit 2c7027d2b5901fb607046e60db650b034e12e261. Without the roundtrip it was possible that session_lock_surface_destroy gets called before unlock_and_destroy is processed.
fixes #107
=> Revert "core: dispatch on exit instead of roundtrip"

CMakeLists.txt, pam/hyprlock, src/core/Password.cpp
This pull request would make hyprlock use it's own pam configuration file instead of the `su` one
This allows the user to include random pam services into it without touching stuff required by other programs.
By default, this just includes the `/etc/pam.d/login` configuration, which contains, by default:
```
#%PAM-1.0
auth       required     pam_securetty.so
auth       requisite    pam_nologin.so
auth       include      system-local-login
account    include      system-local-login
session    include      system-local-login
password   include      system-local-login
```
Basically just asks for a password.
Creating a custom pam configuration is exactly what https://github.com/hyprwm/hyprlock/issues/4 is asking for, and that issue is therefore fixed by this PR
On a sidenote, I'm not really …
=> Adding a pam configuration file

src/core/hyprlock.cpp
e7fca0abd494fbc3c364ff380c7169522a281a14 fixes a red screen that is quite easily reproducible by moving the mouse a lot during the grace period.
I have yet to figure out how unlock is getting called multiple times consecutively, but now we print an error in this case and just continue, since we have already set m_bTerminate to true.
5b93762583be107bb6b0574eb619ee97195c4f67 fixes the hangs mentioned in #114.
=> Fix unlock sync

src/renderer/widgets/PasswordInputField.cpp
The colors in the outline and quadrant of the hidden input field aren't random because it lacks a seed; it always repeats the same color pattern: yellow, yellow, blue, blue, magenta, pink, green, magenta and so on. I'm unsure if this is the intended behavior, but this should fix it.
=> hidden-input-field: add seed for random colors in hidden input field outline

src/core/hyprlock.cpp
Fedora user back again. Not sure if many people were having this issue but if I don't type anything and hit enter hyprlock would crash and I would just get a red screen.  Added a check to see if the password is not an empty string before authenticating.
=> Test if user is submiting empty string for password

src/renderer/AsyncResourceGatherer.cpp
I used the existing `absolutePath` function with `rawcurrentpath` set to "" in order to expand "~" with ENVHOME.
The resource ids stay the same.
When the path is relative, absolutePath returns an empty option and it would use the original string.
That code path is kind of useless and maybe it would be better to just expand "~" outside of absolutePath.
Behaviour would be the same though.
Fixes #38
=> Support background paths relative to the home directory

nix/hm-module.nix
Fixes dots_rounding and rounding
=> Fix nix home manager module

src/core/Password.cpp, src/core/hyprlock.cpp
This reverts commit 6a085d7f8ea2e4092c3dae2042893489a504ff7c.
This should be handled by the distros pam configuration. There are actual use cases for an empty password.
Fixes #138
=> Allow and fix empty passwords

src/renderer/widgets/Label.cpp, src/renderer/widgets/Label.hpp
When a label gets updated more than once a second, `time(nullptr)` does not have enough precision.
=> label: higher precision resource ids

src/renderer/Renderer.cpp, src/renderer/widgets/Label.cpp, src/renderer/widgets/Label.hpp
#147 Did not fully do the trick.
When  `frameCallback` is set, the `render` function will instantly return. That will make onAssetCallback not update the asset via renderSuper and the label get's stuck with it's current asset until the next render.
31cbb83b824605b5aef0516f0d113644a93fb131 is what fixes the problem.
ed9c1c29aafc76be3e9fd75b9697d66a7f239ec4 was just to check my sanity but it seemed like a sensible change so I left it in
The fix from #147 is not really needed any more since it is now handled via the callback.
Fixes #105
=> Fix label update

src/core/hyprlock.cpp
Poll will return when it catches any signal. 
I used `SIGUSR2` to register a signal that does nothing, so that we can use it for terminating the poll thread without any coredumps. 
To clarify the need for the signal handler: When we `pthread_kill` and poll is currently blocking, then it would not coredump anyways. But if we `pthread_kill` and the poll thread is currently not blocking, then it would core dump without a handler.
If you would signal SIGUSR2 to the whole process while hyprlock is running, then nothing would happen.
The `sigaction` change is just because it is more consistent and could prevent a future headache on a weird system.
Fixes #149
=> core: terminate the poll thread

nix/hm-module.nix, src/config/ConfigManager.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
- pango-parseable `fail_text` with `$FAIL` as pam fail-reason
- `fail_color` to change untagged text color and outer color
- `fail_transition` to configure transition time between `outer` and `fail`
- temporarily resize input-field if fail-message is too long
should fix #97 (https://github.com/hyprwm/hyprlock/issues/97#issuecomment-1981655505)
also accidentally fixed #144, but i'm not sure, maybe it is intended behaviour?
if so, i'll just add check in resize thing to not reshadow if `fade_on_empty = true`
i definitely focked-up somewhere, so double-check plz :heart:
https://github.com/hyprwm/hyprlock/assets/130279855/e09d91ab-80b3-4156-8d8e-775d39e96016
=> input-field: fail display improvments

src/renderer/AsyncResourceGatherer.cpp, src/renderer/widgets/Background.cpp
When there is only a background widget on the surface and the first render fails to get the resource from the gatherer the background will not get rendered.
490fe4bb42615c8f3684300b1dfbe8561781b44b fixes that
The other two commits allow the background to fall back to the background color if cairo fails to handle the path.
Hope TEXTURE_INVALID is the right thing to use for that.
Fixes #155
=> background: handle missing assets

src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/widgets/PasswordInputField.cpp
Only counts codepoints, which is fine, since you can only enter one at a time anyways.
Fixes #129
=> input-field: display utf-8 codepoint length

src/config/ConfigManager.cpp, src/helpers/MiscFunctions.cpp, src/helpers/MiscFunctions.hpp, src/renderer/AsyncResourceGatherer.cpp
Using weakly_canonical avoids a runtime error when the path does not exist.
`absolutePath` now does not check if the file exists. That is done later on anyways.
=> misc: path handling improvements

src/core/Timer.cpp, src/core/Timer.hpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/widgets/IWidget.cpp, src/renderer/widgets/IWidget.hpp, src/renderer/widgets/Label.cpp
reasons behind: https://github.com/hyprwm/hyprlock/pull/150#issuecomment-1987201385
by default force update is disabled and can be enabled with:
`[update:12345:1]` or `[update:12345:true]`
are you ok with parsing like that? i think it makes more sense than config option
=> core: force update labels on `SIGUSR2`

nix/hm-module.nix, src/config/ConfigManager.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
`check_color` to change outer when waiting for check
- shadow animated on fade (not so heavy as i thought)
- resize extra width on fail kinda animated a bit now
- fixed fail counter not updated on empty password input (if no `fade_on_empty`)
=> input-field: `check_color` + some fixes

nix/hm-module.nix
Currently shadow options wrongfully apply to backgrounds in the nix hm module.
@fufexan
=> Nix/HM module: remove shadow options from backgrounds

nix/hm-module.nix, src/config/ConfigManager.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
- `capslock_color`
- `numlock_color`
- `invert_numlock` change color when numlock off (for those who rely on numpad, like me)
- `bothlock_color` when both conditions
by default `color` options are `-1`, which means ignore state
that's ok? or maybe add default colors but leave ability to set `-1`
i don't know how to handle this correctly in Home Manager, as not on Nix
should i just use
```nix
capslock_color = ${toString background.capslock_color}
```
and which type to set then?
now function looks way more cleanly and other stuff can be added easier
=> input-field: add capslock and numlock options

src/renderer/AsyncResourceGatherer.cpp, src/renderer/AsyncResourceGatherer.hpp
Just some misc things I noticed.
=> asyncResourceGatherer: skip processing screenshot paths and remove initThread

src/core/hyprlock.cpp, src/renderer/widgets/IWidget.cpp
should resolve #179 
should resolve #180
`$ATTEMPTS[blabla]` can be used to show blabla or nothing when no failed attempts
https://github.com/hyprwm/hyprlock/assets/130279855/f68dc058-b7f1-448d-a1cb-c7196bfe8f96
one thing to mention, when `$ATTEMPTS` used in cmd, sometimes failasset in input-field doesn't draw
maybe smth could be done?
when `sleep 0.1` is the first command in `cmd`, all ok
=> label: add `$FAIL` and `$ATTEMPTS`

src/core/hyprlock.cpp
Opened my laptop and had no input. Attached and everything looked ok but no key events and a lot of calls to `handleKeyboardKeymap`.
So I don't know if that fixes it but according to [here](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_keyboard) the region should be mapped with MAP_PRIVATE.
The debugger also showed `fd: 0xf (/dev/shm/wlroots-kgkhkA (deleted))`. when stepping through `handleKeyboardKeymap`. But the "(deleted)" part could also be fine. don't know.
Could address #101
=> core: mmap keymap buffer with MAP_PRIVATE

nix/hm-module.nix, src/config/ConfigManager.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/Renderer.cpp, src/renderer/widgets/Shadowable.cpp
Fades out the lockscreen on successful authentication. Closes #60.
https://github.com/hyprwm/hyprlock/assets/84299080/5e74e3fc-57b8-4ea0-9894-07e80e72bff0
**Note about Nix module: **
I can't test it on Nix as I don't use it. If it doesn't work on Nix please tell me to remove that part, I'd be glad to do so.
=> renderer, Nix/HM module: add fade out animation and property to disable

src/renderer/widgets/PasswordInputField.cpp
=> input-field: fix missing `fail_text` when `placeholder_text` is empty

src/core/hyprlock.cpp, src/core/hyprlock.hpp
Wanted the fade out animation for grace unlocks as well.
But also:
- disables input once the fade has started
- renders after the fade out started (needed for grace unlock, fine for normal unlocks as well I guess)
- don't disable the fade out for other compositors (not really needed)
=> core: fade out improvements

nix/hm-module.nix, src/config/ConfigManager.cpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/Renderer.cpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/Image.hpp
that's a simple implementation, just to draw a circle with picture
mostly copy-pasted from background widget and input-field :p
close #10
```ini
avatar {
border_color = 0xffdddddd
border_size = 4
size = 150
position = 0, 200
halign = center
valign = center
}
```
&check; Shadowable
=> widgets: add Image

src/core/hyprlock.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
- correctly erase utf8 chars on backspace
- don't draw outer at all if `outline_thickness = 0`
- don't draw hidden input quadrants on fades. even if respecting `fade.a` and `data.opacity`, it's colored and still visible like quadrant (ugly)
- don't draw dots on unlock fadeout (they are flashing now)
- don't stuck on `check_color` on unlock fadeout
- now correctly checks `dots.currentAmount` against utf8 in draw return
I also made input-field fades to be a bit longer
=> input-field: various fixes

src/core/Egl.cpp, src/core/Egl.hpp, src/core/hyprlock.cpp
Hello!
I was running into a couple of segfaults caused because of the lack of de-initialization of certain components. I thought I would track it down and send in a fix!
The segfault I was really concerned by was caused by the lack of call to `eglTerminate` as it caused a segfault to get thrown from deep within `libnvidia-egl-wayland.so`.
=> Add missing destructors causing segfaults

nix/hm-module.nix, src/config/ConfigManager.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
- new `swap_font` option (see on videos)
- now when `outline_thickness = 0` (aka borderless) inner box color will be changed instead
this is how it looks
borderless with `swap_font`:
will change dots color to inner, that's for cases bright font looks ugly on colored box
https://github.com/hyprwm/hyprlock/assets/130279855/19d8b855-b1db-48e6-bcc0-ec33c30f458b
normal with `swap_font`:
will swap inner and font on check and failure
https://github.com/hyprwm/hyprlock/assets/130279855/c3db7b0f-e3d6-47d8-93ca-4bec19f44834
now i think we should deprecate `fail_transition` in favour of `color_transition`
how it is handled correctly?
=> input-field: new color features

src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/Renderer.cpp, src/renderer/widgets/Label.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
Avoids rendering multiple times on all monitors when having multiple input fields.
=> input-field: only render the current output on fade out callback

src/core/Password.cpp, src/renderer/widgets/IWidget.cpp
This is to fix getlogin() returning (null) under certain systems (e.g. https://github.com/hyprwm/hyprlock/issues/203 and https://github.com/hyprwm/hyprlock/pull/104)
=> Use getpwuid(getuid()) instead of getlogin()

src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/widgets/IWidget.cpp
supports format `$LAYOUT[en,РУС,anystring]`, basically same as in `hyprland.conf` or swayconfig can be used for short names
closes #162
https://github.com/hyprwm/hyprlock/assets/130279855/3baecb0e-8679-4fa2-9c9b-58117bd262c3
not `$LANG` because currently normal env vars are expanded, and LANG is a common one
if (i hope when) #205 get merged, this could be added also as placeholder var
one minor issue, when `XDG_CURRENT_DESKTOP` is not Hyprland, if shadows are enabled for the label and hyprlock launched not with default (0) layout, it seems like shadows applied multiple times for first time, when layout switched - all ok
=> label: add `$LAYOUT` variable

nix/hm-module.nix
Defaults for backgrounds and input-fields make sense.
Don't want it to generate a config with an image that does not exist. It is reasonable to use hyprlock without labels and images I think.
=> Nix/HM module: empty defaults for images and labels

src/config/ConfigManager.cpp, src/core/hyprlock.cpp
Added an `ignore_empty_input` configuration option, for users like myself who often use the enter key to wake the screen.
=> config: add option to ignore empty input

src/core/Output.cpp, src/core/Output.hpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/Renderer.cpp
that's it? or should it be `desc:`
closes #137
=> config: allow mon description for `monitor` value

.gitignore, src/renderer/Texture.cpp, src/renderer/Texture.hpp
Fixes #223
Tested it a bit. Seems to fix it.
Also sneaked in some `.gitignore` additions.
=> label: destroy texture

nix/hm-module.nix, src/config/ConfigManager.cpp, src/helpers/Vector2D.cpp, src/helpers/Vector2D.hpp, src/renderer/Renderer.cpp, src/renderer/widgets/IWidget.cpp, src/renderer/widgets/IWidget.hpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/Image.hpp, src/renderer/widgets/Label.cpp, src/renderer/widgets/Label.hpp
self-explanatory
proper way would be to do it directly with pango/cairo with any angle, and I probably will rework when I figure out how (particularly getting new rotated extents)
=> widgets: add `rotate` option to label and image

src/renderer/widgets/IWidget.cpp
Adds a `$DESC` variable that populates with the user GECOS field, which is commonly used for a display name in login managers, etc.
e.g. 
$USER = linux-user
$DESC = Linux User
=> widgets: add user description variable

nix/hm-module.nix, src/config/ConfigManager.cpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/AsyncResourceGatherer.hpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/Image.hpp
close #225
- `reload_time` -  interval in secs to reload, if 0 can be reloaded with `SIGUSR2`
- `reload_cmd` - command to obtain new path, if empty reuse default one
not sure with option names (as always)
considering that only png is supported, I guess main usecase should be converting and then `killall -USR2` in script, if album arts for example
https://github.com/hyprwm/hyprlock/assets/130279855/5e910e96-ca8a-428f-b27e-4d422a7cab6e
mostly copied from label widget
=> image: add reload options

src/renderer/widgets/PasswordInputField.cpp
This makes it so that pressing enter with an empty input field makes the input field fade in and it will only start to fade out when `checkWaiting` is false.
Checked and it does not conflict with #205
Closes #250
=> input-field: fade in when checkWaiting is true

src/core/hyprlock.cpp
Probably fixes the "unlocks" part of #269 
Kind of an important fix so I will tag @vaxerski.
=> core: use --immediate for attemptRestoreOnDeath

nix/hm-module.nix, src/config/ConfigManager.cpp, src/renderer/Renderer.cpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/Label.cpp, src/renderer/widgets/Shape.cpp, src/renderer/widgets/Shape.hpp
that's to close #253
nothing special, except xray
well, despite it's stupid to punch a hole in background, someone may find it useful
I've been messaged to share a config from #247 video for cava bars, and I think updating labels every 33 ms is much more stupid :D
anyways, it is a harmless option after all
https://github.com/hyprwm/hyprlock/assets/130279855/53ef3f14-563d-4b75-bd28-23c0a85e246b
dunno, looks ok
also added some minor stuff to Image
=> widgets: add Shape + minor image improve

nix/hm-module.nix, src/config/ConfigManager.cpp
Duration of the fail text getting displayed is 1 sec as well. So now switching back to the normal placeholder text and fading out does not happen at the same time.
=> input-field: increase default fade_timeout

nix/hm-module.nix, src/config/ConfigManager.cpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/widgets/Label.cpp
instead of messing with multiple labels with its' own alignments and shadow FBs, let pango do the job
there are more fancy stuff that could be added, like justify and ellipsize with explicit width and height, but I don't think it is relevant in context of a locker
or is it?
=> label: add `text_align` option for multi-line text

.gitignore, CMakeLists.txt, nix/default.nix, src/helpers/Jpeg.cpp, src/helpers/Jpeg.hpp, src/helpers/Webp.cpp, src/helpers/Webp.hpp, src/renderer/AsyncResourceGatherer.cpp
Most of the code is copy-pasted from [hyperpaper](https://github.com/hyprwm/hyprpaper) (with some changes).
Ideally, the jpeg / webp loading code would be shared in some common library. However, I couldn't find a fitting candidate in [hyprwm](https://github.com/hyprwm).
fixes #221
=> Add support for JPEG and WEBP background images

README.md
Fix a little markdown oopsie by splitting a line.
=> readme: add new line for clarity

README.md
Dependency added in 415262065fff0a04b229cd00165f346a86a0a73a. It has a weird name in Fedora as well.
=> add libmagic dependency to README

src/core/hyprlock.cpp, src/core/hyprlock.hpp
Allows users to hold backspace to delete the password buffer.
I feel like using a shortcut to clear the entire buffer is superior, but oh well.
A minor thing to consider:
If you press down a key, press&hold backspace after that and then release the first key, that will cancel the timer. Idk if we want to make sure that the key we are releasing is a repeatable one or not and only cancel if it is. That would fix that.
Also we don't necessarily need to move sym into a separate function, but it made more sense to me like that.
Closes #263
=> core: add key repeat for backspace and make del clear the input

src/config/ConfigManager.cpp, src/renderer/Renderer.cpp
closes #297
Adds the ability to change the order widgets are rendered. Large numbers will be rendered above small numbers (`zheight = 1` will be rendered above `zheight = 0`). All widgets default to 0, except for background which defaults to -1.
=> add zindex option to widgets

src/core/LockSurface.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/widgets/IWidget.hpp
with all of these commits, hyprlock launches, renders and unlocks without a single complaint from asan.
short run without them `SUMMARY: AddressSanitizer: 223640 byte(s) leaked in 2441 allocation(s).`
short run with them.
```
[LOG]   | got iface: wl_seat v9
[LOG]    > Bound to wl_seat v9
[LOG]   | got iface: wl_data_device_manager v3
[LOG]   | got iface: wp_tearing_control_manager_v1 v1
[LOG]   | got iface: wp_fractional_scale_manager_v1 v1
[LOG]    > Bound to wp_fractional_scale_manager_v1 v1
[LOG]   | got iface: zxdg_output_manager_v1 v3
[LOG]   | got iface: wp_cursor_shape_manager_v1 v1
[LOG]    > Bound to wp_cursor_shape_manager_v1 v1
[LOG]   | got iface: zwp_idle_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_relative_pointer_manager_v1 v1
[LOG]   | got iface: …
```
=> few reported leaks by asan

src/renderer/widgets/Image.cpp, src/renderer/widgets/Label.cpp
Fixes crash on unlock:
```
Stack trace of thread 28180:
#0  0x00007f90566a2efc __pthread_kill_implementation (libc.so.6 + 0x8fefc)
#1  0x00007f9056652e86 raise (libc.so.6 + 0x3fe86)
#2  0x00007f905663b9bf abort (libc.so.6 + 0x289bf)
#3  0x00000000004412cb _ZL20handleCriticalSignali (hyprlock + 0x412cb)
#4  0x00007f9056652f30 __restore_rt (libc.so.6 + 0x3ff30)
#5  0x0000000000439e60 _ZN6CTimer6cancelEv (hyprlock + 0x39e60)
#6  0x0000000000470d81 _ZN6CLabelD1Ev (hyprlock + 0x70d81)
#7  0x00000000004710e9 _ZN6CLabelD0Ev (hyprlock + 0x710e9)
#8  0x0000000000444562 _ZN9CRendererD1Ev (hyprlock + 0x44562)
#9  0x00000000004430ac _ZN9CHyprlock3runEv (hyprlock + 0x430ac)
#10 0x0000000000416529 main (hyprlock + 0x16529)
#11 0x00007f905663d10e __libc_start_call_main (libc.so.6 + 0x2a10e)
#12 …
```
=> handle null timers in destructors

src/core/hyprlock.cpp
Fixes #373
I noticed that the `onLockFinished` function calls `ext_session_lock_v1_unlock_and_destroy`, whereas Swaylock on the other hand directly calls `exit(2)` once it notices that a second lock is already running (see [this line](https://github.com/swaywm/swaylock/blob/b70d85ec145520ba3ebaa4c51921a2761bc0c7f0/main.c#L282)). Implementing this fix alone, however, did not resolve the problem. Thus, I dug further and noticed, that moving the call to `wl_display_roundtrip` after `acquireSessionLock` now seems to resolve the issue.
I have to admit that I have no idea about Wayland and their protocols, so please throw this code out of the window if it makes no sense at all.
=>  fix second instance of hyprlock unlocking session

src/core/LockSurface.cpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/AsyncResourceGatherer.hpp, src/renderer/widgets/Label.cpp
Was able to repro #357 (multiple monitors required i think).
Fixes it on my end.
[4509552](https://github.com/hyprwm/hyprlock/pull/384/commits/450955217f860554384549f461cf0c080d86a957) reverts the previous approach of adding a timer to re-render, when the resource was not available (#152). It also sets `needsFrame=true`, when render is called but `frameCallback` is present (I think not 100% needed but still makes sense)
The other 3 commits make sure that `getAssetById` fails less often by removing the `busy` flag and revisioning the locking in the resource gatherer.
`-fsanitize=thread` is a bit happier regarding the asyncResourceGatherer now. Besides some races with `dmas` on startup I think.
Closes #367
=> core: stabilize label updates and revision locking in the asyncResourceGatherer

src/main.cpp
`handleSource` handle relies on `g_pConfigManager`, which was previously moved after `init`.
Closes #383
=> core: fix sourcing config files

src/core/LockSurface.cpp, src/core/Output.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/AsyncResourceGatherer.hpp, src/renderer/DMAFrame.cpp, src/renderer/DMAFrame.hpp, src/renderer/Renderer.cpp, src/renderer/Renderer.hpp
I reproduced some crashes with the lid switching the internal monitor on and off.
That is because the session lock surface is getting created via `handleDone` for a new output.
Even if a full display roundtrip is done, some events might arrive earlier than the output `done` event causing a crash because the `sessionLockSurface` pointer is null. Checking for the `sessionLockSurface` pointer fixes that. Other option would be to only add dynamic outputs to the `m_vOutputs` vector when the sessionLockSurface already exists
Then I noticed that the widgets for a surface are not removed, when it is destroyed (I think that caused #337). Sometimes the new `sessionLockSurface` happens to be the same pointer as the original one. And because the widgets map is keyed by those pointers it will reuse …
=> core: improve dynamic output handling

src/renderer/AsyncResourceGatherer.cpp
Fixes a race that now shows itself since https://github.com/hyprwm/hyprlock/pull/386, because if the added check to fall back to background color for dynamic backgrounds.
Thats because `gather` waits for all dma frames to be ready, but rarely it was possible that not all dma frames have been added yet in the `asyncResourceGatherer` ctor.
=> asyncResourceGatherer: add dma frames before starting the asyncLoopThread

src/config/ConfigManager.cpp
Very small PR, removes a code line which seems redundant, likely a copy paste typo.
=> Remove dupe input-field rounding from listKeysForSpecialCategory

src/renderer/widgets/IWidget.cpp
Currently `cmd[]` will cause the following error `[ERR] Unknown prop in string format`.
Since I think it makes sense to use it like that for a static label command, I set `removeEmpty` for the `CVarList` ctor.
Then I noticed `removeEmpty` does not affect empty inputs, so I figured It would make sense if it did. Thus https://github.com/hyprwm/hyprutils/pull/7.
=> label: do not error when using cmd[] for a static label cmd

src/config/ConfigManager.cpp
Do we prefer throwing an error like this, or logging + exit or just returning an empty string?
Same problem in hyprland as well.
Closes #392
=> config: don't crash when getenv HOME returns null

src/core/Auth.cpp
Changed the log, because someone used an absolute path for `general:pam_module`.
Also new release maybe?
People that use 0.3.0 are quite a bit behind by now and don't have d9f644125468054d2a237adf4ae676f64c0da918.
=> auth: pam fallback log message and always call pam_end after pam_authenticate

src/helpers/Jpeg.cpp, src/helpers/Webp.cpp
Following the cairo docs on [cairo_surface_mark_dirty](https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-mark-dirty), the cairo surface flush call had been left out and was leading to OOM errors on non-png images. This should fix that issue.
Resolves #315.
=> helpers: fix jpeg and webp OOM error

src/core/hyprlock.cpp
if the unique_ptr is reset directly accessing it from the destructor causes crashes on Clang/libc++, just access the members directly.
fixes #403
=> hyprlock: ensure members are accessed direct

src/config/ConfigManager.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/main.cpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/AsyncResourceGatherer.hpp, src/renderer/Renderer.cpp, src/renderer/Renderer.hpp, src/renderer/widgets/Background.cpp, src/renderer/widgets/Background.hpp
Closes #389
Option and flag that allows `background:color` to be rendered immediately, when the background assets are not ready yet.
=> core: add option to render solid background immediatly when bg assets are not ready

src/core/Auth.cpp
After realizing that pam modules sometimes implement a timeout, i think it is not worth starting the convo it right away.
Now you won't get the initial PAM_PROMPT any more. Prompt will be initialized to "Password: ", which is most commonly what you get from pam. Subsequent prompts (e.g. 2fa) will be handled however.
=> [Draft] auth: don't start pam conversation before the initial input happens

src/renderer/AsyncResourceGatherer.cpp, src/renderer/widgets/Label.cpp
Trace logs should help debug label update problems.
`dmas.clear` in the asyncLoopThread sometimes caused a crash. So i removed it. Will get destroyed together with the asyncResourceGatherer. Also tought clearing requests would be a good idea when calling `AsyncResourceGatherer::notify`.
=> asyncResourceGatherer: trace logs and exit behaviour

src/core/hyprlock.cpp
Closes #416
According to [ext_session_lock_v1::finished](https://wayland.app/protocols/ext-session-lock-v1#ext_session_lock_v1:event:finished)
>  Upon receiving this event, the client should make either the destroy request or the unlock_and_destroy request, depending on whether or not the locked event was received on this object.
Also `exit` previously did not terminate hyprlock properly. I think the right thing to do is to set `m_bTerminate`.
=> core: handle ext_session_lock_v1::finished as defined by the protocol

src/core/hyprlock.cpp, src/core/hyprlock.hpp
Instead of waiting for the `locked` event, create session lock surfaces right away.
Closes #420
=> core: immediately create session lock surfaces

src/core/Auth.cpp, src/core/Auth.hpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp
Closes #423
Grace code previously respected the case when `m_bFadeStarted` was already set, but not `m_bTerminate` in case `gerneral:no_fade_out` is used.
Auth needs to check for `isUnlocked` to not cause a failed authentication attempt. Also we don't need to enqueue `passwordCheckTimerCallback` if we are already unlocked.
I didn't like `success` being part of `m_sConversationState`. So I moved it outside of it, used the return value of `auth` to set it and renamed it to `m_bAuthenticated`.
https://github.com/hyprwm/hyprlock/pull/424/commits/b6d2be62184dc3e06ed73f16d1ef4211d1433617 is just in there because i noticed it.
=> core: grace unlock improvements and auth fixes for grace/SIGUSR1 unlocks

src/renderer/AsyncResourceGatherer.cpp
Also makes the image widget support JPEG and WEBP.
Tested all three file types and backgrounds still render the same.
=> asyncResourceGatherer: deduplicate image rendering code

src/renderer/widgets/Image.cpp, src/renderer/widgets/Image.hpp, src/renderer/widgets/Label.cpp, src/renderer/widgets/Label.hpp
This allows us to check if the label has actually updated after the
callback from the asyncResourceGatherer. If it isn't we can requeue the
renderUpdate() function.
Probably fixes #390
=> widgets: move asset updates out of the draw function

src/main.cpp
Saw the recent commit about `--version` and while reading the code did a small refactor.
Nothing special, put a newline between each "argument block", moved `--help` on top (check and eventually exit) and removed the `showHelp` variable since it's not needed below.
=> core: refactor command line options parse (minor)

src/core/Auth.cpp, src/core/Auth.hpp
Allows us to show "(x minutes left to unlock)" directly in the input-field fail text.
I thought about how to best include the faillock message from pam_faillock. I considered the following options:
- Create a separate variable like `$PAM_LOG` that includes the entire pam log.
Problem is that there are multiple lines and that does not work nicely in the input's placeholder text.
- Just look for the specific message and set it as `$FAIL` (This MR).
Does not work if the message is translated.
Picked the second option, because I think it is more useful and works with the default value for `input:fail_text`
But it feels a bit hacky, so if anyone has a better idea, let me know.
=> auth: use pam_faillock log as $FAIL

src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/main.cpp, src/renderer/Renderer.cpp
This PR implements what I wished for in https://github.com/hyprwm/hyprlock/issues/452
It simply adds a `--no-fade-in` flag that disables the fade in animation when used, overwriting the use of no_fade_in (as if it was always set to true).
For the implementation, I mainly looked at the way `--immediate-render` was implemented.
LMK if there are any changes I should make, the main doubts I have are:
* is the internal `m_bNoFafeIn` name correct? not sure what the m and the b stand for.
* the commit name, should it start with `renderer:`? Would something else like `core:` be better?
=> renderer: add `--no-fade-in`

src/config/ConfigManager.cpp, src/core/LockSurface.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp
Allows users to enable and disable fractional scaling.
The auto option is default and enables fsv1 when on Hyprland or Niri.
Scaling of lock surfaces is currently broken on sway & river.
Closes #439
=> core: add fractional_scaling option

src/core/LockSurface.cpp, src/core/LockSurface.hpp
Fixes dynamic output updates via programs like kanshi or wdisplays. (Ref #65)
Accidentally fixed fractional scaling on river and sway (hence e34f67a4f9a861bd05fb5a4a237b4539ea45bf70).
Turns out wlroots sends a correct configure event at some point, but we already created widgets with a wrong viewport. So dynamically removing them fixes it.
Now instead of destroying all widgets for the surface, we could also just update the viewport of all widgets.
Did not do that yet, since I did not want to give the IWidget base class a state and did not feel like implementing a viewport setter for all widgets. Let me know which one of the two sounds better, or if removing like this is fine (widgets will just get recreated with `getOrCreatedWidgetsFor`).
=> lockSurface: fix dynamic output mode and scale updates

src/core/hyprlock.cpp
Hyprlock crashes frequently in my case. When a crash occurs, GDB shows:
1. The main thread is trying to exit, and `CAsyncResourceGatherer` has already been destroyed.
2. `initialGatherThread` is still running, walking through `dmas` of the destroyed `CAsyncResourceGatherer` instance.
Calling await for `initialGatherThread` should fix this specific crash.
=> fix crash caused by exiting without joining running thread

src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
Looked into the `updateColor` code for the input field because of #468.
I did not understand what was going on, so I rewrote the function.
I think it behaves as it did before with all the different options, but now `swap_font_color` and `invert_numlock` work as expected.
Notable is that there are no animations for font color changes (which happen when `outline_thickness=0` and `swap_font_color=1`). As reported in #468 those options are currently broken.
I implemented animations for the font, but making subsequent requests to the asyncResourceGatherer with changing colors is not nice and lead to some problems. So the `updateColors` function just sets the font color without animating it.
I did quite a bit of testing but if someone can double check if everything works that would be …
=> input-field: refactor updateColors and other improvements

src/renderer/Renderer.cpp
Just adds the possibility to use `desc:` in widgets monitor options.
As mentioned in https://github.com/hyprwm/hyprland-wiki/pull/746.
=> core: support desc: prefix for widget monitor options

src/renderer/AsyncResourceGatherer.cpp
Worker threads become non-joinable once they are detached, and `await()` will not wait for them to finish. This can lead to a crash when `asyncResourceGatherer` is destroyed in the main thread while it is still being used in worker threads.
It crashes several times daily in my case without this patch.
=> asyncResourceGatherer: do not detach worker threads

src/core/hyprlock.cpp
`attemptRestoreOnDeath` only works with hyprland anyways.
This is why we now use `hyprctl dispatch exec` to relaunch hyprlock. Removing the need to `disown` the process.
Destoying the lock and lockSurfaces right away also allowed me to remove the `sleep 2 &&` part of the previous recover command and launch it in sync.
Fixes #504
=> core: make attemptRestoreOnDeath faster and hyprland exclusive

src/config/ConfigManager.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
Adds a config option `dots_fade_time` to `input-field` to control how many milliseconds it takes for dots to fade in and out while typing. Anything <= 0 is instant, disabling dots fading. The default is 200ms which is the same as before.
Closes: https://github.com/hyprwm/hyprlock/issues/355
=> config: add input-field dots_fade_time option

src/config/ConfigManager.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
This adds an option, that allows setting an arbitrary char to be rendered instead of a rectangle for the input fields dots.
Closes #316
Closes #482
Let me know if you think we should name the option something else.
Guy in #316 suggested `dots_mask_character`. Maybe just `dots_char`?
Currently the option does support multiple chars as well, so I chose `dots_text`. But in that case `dots_text_format` is a bit more clear I think.
I also added the `font_familiy` option to the input-field, in order for users to be able to use a nerd font for example.
=> input-field: add dots_text_format to support setting arbitrary chars as the input indicator

src/renderer/Framebuffer.cpp
This just spams the logs and doesn't seem to be adding any valuable information.
=> renderer: log framebuffer creation as trace

CMakeLists.txt, nix/default.nix, nix/overlays.nix, src/config/ConfigManager.cpp, src/core/Fingerprint.cpp, src/core/Fingerprint.hpp, src/core/hyprlock.cpp, src/renderer/widgets/IWidget.cpp
I chose to use Fprint's dbus interface directly rather than going through pam (which uses Fprint's dbus interface) due to poor handling of system sleep somewhere between fprintd and pam. When preparing for sleep, fprintd puts the device to sleep, which causes VerifyStatus to emit with verify-unknown-error, which normally should be responded to by calling both Device.StopVerify and Device.Release (and this is what pam does). Unfortunately, if you try to release the device when the system is preparing for sleep, you'll get an error that the device is busy and then you can't can't claim or release the device for 30 seconds.
pam also has a max timeout for pam_fprintd.so of 99 seconds, and so if we used pam, we'd have to deal with the timeouts and keep restarting the auth conversation. …
=> auth: Support parallel fingerprint auth

src/helpers/Log.hpp, src/renderer/widgets/IWidget.cpp
Just to be sure we don't deref that if it is not set.
Probably fixes https://github.com/hyprwm/hyprlock/issues/519
=> widgets: check current_zone pointer

src/helpers/Log.hpp
Makes it a lot easier to spot a failed RASSERT
=> misc: make Debug::log flush stdout

src/core/Fingerprint.cpp, src/core/Fingerprint.hpp
Communicating over dbus and waiting for fingerprint device initialization can take long enough to delay the first draw and potentially display the recovery screen, so this switches to initialize fingerprint support asynchronously.
Fixes #543
=> auth: make fingerprint initialization async

src/config/ConfigDataValues.hpp, src/config/ConfigManager.cpp, src/helpers/MiscFunctions.hpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/Label.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/Shape.cpp
Adds the ability to specify `size` and `position` options as percentages of the output viewport.
E.g.
```
position = 10%, 10%
size = 10%,5%
```
This is allowed:
```
position = 10%, 10
```
~Question: Do we want to support a `px` suffix to allow more explicitness?~ This is also allowed:
```
position = 10%, 10px
```
To allow users to make layouts that are independent of the output viewport we are missing `label:font_size` and `image:size` (which should be `image:scale` fmpov, but for some reason it was named size...)
But I think it is easier for us to do that in a separate MR.
Part 1 to implement #261
Closes #446 (`halgin=left` and `position = 50%, 0`)
=> widgets: add support for specifing size and position options via percentages of output dimensions

src/config/ConfigDataValues.hpp, src/config/ConfigManager.cpp, src/helpers/MiscFunctions.cpp, src/helpers/MiscFunctions.hpp, src/renderer/Renderer.cpp, src/renderer/Renderer.hpp, src/renderer/Shaders.hpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/Image.hpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp, src/renderer/widgets/Shape.cpp, src/renderer/widgets/Shape.hpp
Allows all sorts of nice theming stuff.
`changeGrad` also looks pretty cool when used with gradients.
Also thought about some kind of rotate option to let the gradient rotate, when auth is checking. Maybe in the future.
Closes #458
=> core: add border shader and border gradients

src/helpers/Color.cpp, src/helpers/Color.hpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/Shape.cpp
I broke shape and image borders on accident by using `data.opacity`.
Did not realize it because i don't use fade-in.
CC @alba4k
=> widgets: render frambuffers with alpha 1.0

src/helpers/MiscFunctions.cpp
Broke decimal support in rgba with #548.
This brings it back.
Implementation copied from hyprlang. Removed std::expected though.
=> config: make configStringToInt support rgb(a) with decimal values

src/config/ConfigDataValues.hpp, src/config/ConfigManager.cpp, src/renderer/widgets/PasswordInputField.cpp
The `m_vColors.empty()` check did not work like i thought it would.
To differentiate between legitimate `CColor(0)` with angle 0, I added this `m_bIsFallback` boolean. Other option would have been to allow `m_vColors` to be empty, but I think that is not a good idea.
=> input-field: fix colorConfig caps, num and both when they are empty

src/config/ConfigManager.cpp
Fixes parse errors when parsing an empty string
=> config: use removeEmpty for the gradient varlist

src/renderer/Renderer.cpp
Fixes https://github.com/hyprwm/hyprlock/issues/534
`wlr_matrix_project_box` implicitly casted the box
```cpp
int x      = box->x;
int y      = box->y;
int width  = box->width;
int height = box->height;
```
This brings it back explicitly fixing blurry textures.
=> renderer: round boxes

CMakeLists.txt, flake.lock, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/AsyncResourceGatherer.cpp
Only thing is that now stderr is not printed. Maybe we want to print that if it's not empty?
Closes #574
=> core: move to Hyprutils::OS::CProcess for spawning processes

src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
This fixes some problems with the input field resize. 
- support fading to a smaller size
- don't draw the shadow when fading
- don't draw the asset when the input field size is to small
Motivated me to start porting hyprlands animation manager to hyprlock.
=> input-field: fix width animations

src/auth/Auth.cpp, src/auth/Auth.hpp, src/auth/Fingerprint.cpp, src/auth/Fingerprint.hpp, src/auth/Pam.cpp, src/auth/Pam.hpp, src/config/ConfigManager.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/widgets/IWidget.cpp, src/renderer/widgets/PasswordInputField.cpp
This has the goal to create an interface that hyprlock uses for authentication.
After this, error messages from fingerprint can be shown in the PasswordInputField by using `$FAIL` in `input-field:fail_text`. The input field will actually show a failure when we failed to match now as well.
BREAKING:
- `general:pam_module` -> `auth:pam:module`
- `general:enable_fingerprint` -> `auth:fingerprint:enabled`
- `general:fingerprint_ready_message` -> `auth:fingerprint:ready_message`
- `general:fingerprint_present_message` -> `auth:fingerprint:present_message`
Implicit changes introduced by this PR:
- Attempts now also factor in the failed attempts from fingerprint auth.
- A fingerprint swipe clears the password input buffer.
=> auth: add an interface for different authentication methods

src/core/hyprlock.cpp
This probably fixes https://github.com/hyprwm/hyprlock/issues/577
=> core: terminate auth after recieving `finished`

CMakeLists.txt, src/main.cpp
Opted for doing it straight in cmake, since we don't need all the stuff that `generateVersion.sh` in Hyprland does.
This only appends the short git hash when we are not on the tag v${VERSION} where ${VERSION} is the content of the VERSION file.
Merging this implies that `Hyprlock version 0.6.0` can be actual v0.6.0, https://github.com/hyprwm/hyprlock/commit/058830668e92e92b3179319090b5d523ba4d59a4 or https://github.com/hyprwm/hyprlock/commit/d12b4a7fbaf570fbe9322c09a777c124fbf15306, since those 2 commit don't have this yet
=> misc: add git commit hash to --version when not on tag v${VERSION}

src/config/ConfigManager.cpp
Regressed by https://github.com/hyprwm/hyprlock/commit/578246b9967dec77c56993dc55ca192d35ba9bb7
Closes #593
Could be a reason to release 0.6.1.
=> core: fix parsing grad with decimal rgb(a) colors

src/auth/Pam.cpp
Note: if this assert fires, it will be before acquiring the session lock.
=> auth: assert username

src/renderer/widgets/PasswordInputField.cpp
Closes #600
Will parse `cmd[]` for placeholder_text and fail_text, but it won't be used.
=> input-field: use IWidget::formatString for placeholder_text and fail_text

src/renderer/widgets/Background.cpp, src/renderer/widgets/Image.cpp
Fixes those errors:
```
[ERR] filesystem error: cannot get file time: No such file or directory [screenshot]
[ERR] filesystem error: cannot get file time: No such file or directory [~/media/picture/wal.png]
```
=> widgets: use absolutePath to get last_write_time and ignore when no reloadTime

src/renderer/widgets/IWidget.cpp, src/renderer/widgets/IWidget.hpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/Shape.cpp
Closes #611
To verify that the the outline of a box matches with the inner border perfectly,
I used this:
```
input-field {
monitor=
size=25%, 5%
inner_color=rgba(fff7ed20)
outer_color=rgba(fff7ed20)
position=0, -20
rounding=15
fade_on_empty = false
valign=center
}
```
Because inner and outer color have the same alpha, one can easily spot if they overlap or not.
Previously if the rounding was to big, it used rounding 0.
Now it clamps it to the maximum.
Tested:
=> widgets: algin rect outline radius with inner border radius

src/renderer/widgets/IWidget.cpp
=> widgets: add TZ env var support for $TIME

src/config/ConfigManager.cpp
Closes #622
I missed that Hyprland does not support spaces for rgb(a) either and somehow i thought i broke it. So it is broken since gradients were added.
Not the best fix, but the simplest. Should I add this in Hyprland as well?
=> config: fix gradient rgb(a) parsing with spaces (for real this time)

src/auth/Fingerprint.cpp, src/config/ConfigManager.cpp
Add a new config option ("auth:fingerprint:retry_delay") that adds a delay after an unrecognized fingerprint has been scanned. The default delay is 250ms. Currently when an incorrect finger is scanned, it gets scanned as fast as possible which leads to the number of retries being using up extremely quickly.
=> fingerprint: add a delay after an unrecognized fingerprint

src/helpers/MiscFunctions.cpp
Relative path was not handled if input started with tilde.
Examples:
```
~/./test
~/weird/../test
```
No reason to do something like this imho, but users you never know.
Likely not related to https://github.com/hyprwm/hyprlock/issues/639 but worth to mention.
=> helpers: fix absolutePath relative with tilde

src/config/ConfigManager.cpp, src/core/AnimationManager.cpp
The change in the animationmgr is the same as https://github.com/hyprwm/Hyprland/pull/9000.
Also adapted the simplification in `CConfigManager::handleAnimation` from Hyprland.
=> animations: fix overshoot beziers and cleanup animation config parsing

assets/example.conf
Added some default animations to the example config, that replicate old hyprlock behaviour. They both give a pleasant fade animation and provide some hints on how to organize and customize hyprlock.
=> example.conf. Add default animations

CMakeLists.txt
This allows building on a system that:
- Lack GLX support (pure wayland)
- Require explicit declaration for OpenGL::EGL
Basically same as https://github.com/hyprwm/Hyprland/pull/5469.
Fixes: https://github.com/hyprwm/hyprlock/issues/509
Downstream Bug: https://bugs.gentoo.org/947781
Reference: https://gitlab.kitware.com/cmake/cmake/-/blob/0cc144ecfdd0c82f8507e32aba6d2fa364d48941/Tests/FindOpenGL/Test/CMakeLists.txt#L127-131
=> cmake: explicitly require GLES3 component

src/auth/Auth.cpp, src/auth/Auth.hpp, src/auth/Fingerprint.cpp, src/auth/Pam.cpp, src/renderer/widgets/IWidget.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
This PR brings back fingerprint errors in `$FAIL`. That was regressed by https://github.com/hyprwm/hyprlock/pull/603.
BREAKING:
- Removed $PROMPT variable. Either use $PAMPROMPT or $FPRINTPROMPT.
- Removed $FPRINTMESSAGE. Use $FPRINTPROMPT instead. There is also
$FPRINTFAIL.
=> auth: fixup prompt and fail substitution

src/core/LockSurface.cpp, src/core/LockSurface.hpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/Renderer.cpp
This was done, so that we can
wl_display_prepare_read -> poll -> wl_display_read_events
That fixes synchronization issues on nvidia proprietary drivers.
Closes https://github.com/hyprwm/hyprlock/issues/572
Closes https://github.com/hyprwm/hyprlock/issues/525
Closes https://github.com/hyprwm/hyprlock/issues/419
Closes https://github.com/hyprwm/hyprlock/issues/128
=> core: move wayland event reading into the poll thread

src/core/hyprlock.cpp
This fixes a bug that can happen when the rending of a session lock surface is delayed (for example when dmps is off). 
Launching hyprlock during dmps off and then waking the screen ended up in hyprlock being deadlocked.
=> core: don't attempt to unlock when we are not locked yet

src/renderer/widgets/PasswordInputField.cpp
Closes https://github.com/hyprwm/hyprlock/issues/668
=> input-field: fix color updates for BORDERLESS swap_font_color false

src/renderer/widgets/PasswordInputField.cpp
Hyprlock crashes in `updateColors()` when:
- Numlock is enabled.
- `colorConfig.num` is a fallback value.
There is an inconsistency in condition checks when assigning and later using `targetGrad`:
1. **When assigning `targetGrad`** (Line 409), the condition checks both:
- Whether numlock is enabled.
- Whether `colorConfig.num` is **not** a fallback.
2. **When using `targetGrad`** (Line 421), the condition only checks for numlock, but **does not** check if `numlock_color` is a fallback.  
- If `numlock_color` **is** a fallback, `targetGrad` remains `nullptr`, leading to a crash.
- Updated the condition in Line 421 to **match** the condition used when assigning `targetGrad`.
=> input-field: Fix crash when numlock is on and numlock_color is fallback

src/renderer/widgets/PasswordInputField.cpp
In https://github.com/hyprwm/hyprlock/pull/582 I changed it so the placeholder text is not rendered until the dynamic width resizes and the placeholder actually fits.
That however also looks off, especially with slow animation speeds.
This PR changes it so that it will render it right away, but cut it where the input field ends.
Alba and me also thought about fading in the placeholder text, but I think that is smth for a separate PR.
CC @alba4k you wanna test again? I did not include a pad to the input field like you suggested, cause if think it looks better like that.
=> input-field: improve dynamic width

.clang-tidy, src/auth/Pam.cpp, src/config/ConfigManager.cpp, src/core/AnimationManager.cpp, src/core/Egl.cpp, src/core/LockSurface.cpp, src/core/Timer.cpp, src/core/hyprlock.cpp, src/helpers/Color.cpp, src/helpers/MiscFunctions.cpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/Renderer.cpp, src/renderer/Screencopy.cpp, src/renderer/Texture.cpp, src/renderer/widgets/Background.cpp, src/renderer/widgets/IWidget.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/Shape.cpp
I guess that's all
And changed one comment, bc i'm just being picky there
=> clang-tidy and comp fixes

src/core/Output.cpp, src/core/Output.hpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp
Related to https://github.com/hyprwm/Hyprland/pull/9399
Together with the hyprland PR this fixes parts of https://github.com/hyprwm/hyprlock/issues/678. Possibly related to https://github.com/hyprwm/hyprlock/issues/101 as well.
=> core: don't rely on the locked event to create lock surfaces dynamically

CMakeLists.txt
Missing from https://github.com/hyprwm/hyprlock/pull/689 (The warp updates require it)
=> cmake: bump hyprutils version

src/renderer/widgets/Image.cpp
Fixes a regression caused by #686 (Images don't render cause of a missing resourceId)
=> image: set resourceId in configure

src/core/Seat.cpp, src/core/Seat.hpp, src/core/hyprlock.hpp, src/renderer/widgets/IWidget.cpp
Fixes a crash reported in https://github.com/hyprwm/hyprlock/issues/695
=> label: fix crashes when keymap is a nullptr after suspend

src/auth/Auth.cpp, src/auth/Pam.cpp, src/renderer/widgets/PasswordInputField.cpp
Makes more sense than clearing the input buffer in the auth impl. Also added a check for the password buffer length to reset the fail color as soon as the password length > 0.
=> core: move password buffer clearing to handleInput

assets/example.conf
Includes examples from wiki with minor modifications. Date and time labels inspired by https://github.com/catppuccin/hyprlock
Aims to improve out-of-the-box experience and basic stuff reference.
=> assets: update example.conf

src/core/LockSurface.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp
This causes confusion when trying to help people debug or get traces.
I think now that we have the lock dead screen, where recovery options are stated, we don't need this any more.
It can also cause some leakage of the desktop or other weird behavior combined with other bugs. See #695
=> core: remove attemptRestoreOnDeath

src/auth/Auth.cpp, src/auth/Auth.hpp, src/config/ConfigManager.cpp, src/core/hyprlock.cpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp
Initial version of this PR intended to fix some edge cases when rapidly providing input, where you would see the fail color, but no fail text placeholder.
Now it does that plus moving the `input-field:fail_timeout` setting.
It is easier and more flexible to handle the duration for which an auth failure gets displayed outside of the PasswordInputField widget.
Now per input-field fail_timeout settings wont be supported, but that didn't work anyways (smallest `fail_timeout` always took precedence)
=> core: move fail_timeout from input-field to general

src/auth/Fingerprint.cpp, src/auth/Fingerprint.hpp
fprint does have it's own logic to inhibit sleeping until it cancels active tasks. I believe that hyprlock's logic to stop the verification before sleeping was causing an issue within fprint as it tried to handle both at the same time.
I was only having this issue occasionally so I'm not sure this completely fixes it, which is why this is a draft.
=> fingerprint: allow fprint to suspend and cancel verify for us

src/core/Output.cpp
Originally I didn't want to do this, because the protocol clearly wants us to create a lock surface for all outputs.
But when we have size 0x0 we will need to handle it later on and not render onto this surface. I think its better to just omit creating one.
This might be related to some open issues related to suspend and monitor handling.
Cause I think it is currently possible that focus lands on the unsafe fallback monitor after hyprlock creates a lock surface for it.
I will address that in Hyprland as well. I think we should not allow a session lock surface for the fallback output, because we don't want it to receive focus.
=> output: refuse to create session lock surfaces with size 0x0

src/auth/Fingerprint.cpp
When verification fails and a retry is needed (like when the user didn't hold
their finger for long enough) the prompt variable is changed but the widgets
aren't actually updated so the new prompt is never shown to the user. This fixes that.
=> fingerprint: update widgets after changing prompt

src/renderer/Renderer.cpp
Same fix as https://github.com/hyprwm/Hyprland/commit/c2d14a2013b871b5d0b50c39ee781882d68e8b03.
Copied that unfortunately when adding the gradients.
Potentially cause of #741
=> renderer: fix gradient copy size in renderBorder

src/core/Seat.cpp, src/core/Seat.hpp, src/core/hyprlock.hpp, src/renderer/widgets/IWidget.cpp
@geovex I saw your code in https://github.com/hyprwm/hyprlock/issues/739
I pulled it and guarded `g_pSeatManager->m_pXKBKeymap` to avoid the crash that motivated #699.
Let me know if the fix still works for you!
Closes #739
=> core: correct $LAYOUT replacement

assets/example.conf, src/config/ConfigManager.cpp, src/core/CursorShape.cpp, src/core/LockSurface.cpp, src/core/LockSurface.hpp, src/core/Seat.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/helpers/MiscFunctions.cpp, src/helpers/MiscFunctions.hpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/Framebuffer.cpp, src/renderer/Framebuffer.hpp, src/renderer/Renderer.hpp, src/renderer/widgets/Background.cpp, src/renderer/widgets/IWidget.cpp, src/renderer/widgets/IWidget.hpp, src/renderer/widgets/Image.cpp, src/renderer/widgets/Image.hpp, src/renderer/widgets/Label.cpp, src/renderer/widgets/Label.hpp, src/renderer/widgets/PasswordInputField.cpp, src/renderer/widgets/PasswordInputField.hpp, src/renderer/widgets/Shape.cpp, src/renderer/widgets/Shape.hpp
Picks up the contribution from @Memoraike (thanks :))
Implements https://github.com/hyprwm/hyprlock/issues/366.
=> widgets: add onclick feature

src/renderer/Renderer.cpp
Currently, selecting a monitor by its description using the `desc:` prefix (see wiki [here](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#monitor-selection)) does not work due to a small logic bug. This fixes that.
Turns out there also was an issue for that, closes #737
=> renderer: properly treat monitor `desc:` prefix

src/core/Seat.cpp, src/core/Seat.hpp
This treats touch input events as (left) clicks.
Currently the onClick implementation does not care which (mouse) button is used to click on an element. So it might be acceptable to remove the include and use a fixed value (0 or 272). However, this might lead to problems if onClick ever learns to distinguish between different clicks.
This only works for "real" finger touch inputs, (tablet) pen touches are translated to pointer move events, but the tab event does not seem to reach hyprlock.
Tested on a surface go 1 and a thinkpad x1 yoga gen1 with arch.
=> core: treat touch as click

src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/renderer/AsyncResourceGatherer.cpp, src/renderer/AsyncResourceGatherer.hpp, src/renderer/Framebuffer.cpp, src/renderer/Framebuffer.hpp, src/renderer/Renderer.cpp, src/renderer/Renderer.hpp, src/renderer/Screencopy.cpp, src/renderer/Screencopy.hpp, src/renderer/widgets/Background.cpp, src/renderer/widgets/Background.hpp, src/renderer/widgets/Image.cpp
Instead of relying on Hyprland drawing it's workspaces when locked, use a screenshot to fade in and out.
Basically had to rewrite the background widget.
No merging yet. I might revision the background widget.
Needs testing.
Note:
This is supposed to go together with a MR that makes it so Hyprland does not draw workspaces when locked per default. But I have a `misc:allow_session_lock_xray` setting planed to keep it possible to use `shape:xray` or implement dynamic blur.
=> core: use a screenshot for fade in/out

src/config/ConfigManager.cpp, src/core/hyprlock.cpp, src/core/hyprlock.hpp, src/main.cpp
ref https://github.com/hyprwm/hyprlock/issues/782
=> core: replace grace option with --grace cli argument

src/renderer/widgets/IWidget.cpp
fixes: https://github.com/hyprwm/hyprlock/issues/816
=> widgets: remove the libc++ version check

src/renderer/widgets/PasswordInputField.cpp
=> input-field: fix wrong placeholder text for resourceID

src/core/hyprlock.cpp
This PR implements a key bind to clear the password field when `ctrl + a` is pressed.
I found it annoying, then saw [this thread](https://github.com/hyprwm/hyprlock/issues/821) that recommended this approach and decided to contribute.
While it is not ideal, I think it is a better standard result to clear the input rather than type `a` when pressing `ctrl + a`.
I built and tested it locally and it works as expected.
Let me know if I need to add anything else, I'm happy to contribute.
=> Add ctrl+a as binding to clear password

src/renderer/widgets/Background.cpp
- forgot the apply transform when blurring the screencopy in the last fix for transform issues
- render backgrounds to a frambuffer when we have a monitor transform. then render the framebuffer without an explicit transform.
Closes https://github.com/hyprwm/hyprlock/issues/849
=> background: monitor transforms fixups

src/core/Egl.cpp, src/core/Egl.hpp, src/core/hyprlock.cpp
So I have been investigating #793 (Which has a confusing title, but I think all reports are caused by monitor re-plugging). Edit: wrong issue. I wanted to link this one: #695. They might be the same though. I think both probably have nothing to do with suspend per se.
I was able to reproduce the issue on this system:
```
Hyprland 0.50.0 built from branch main at commit 2859f1b795e1e772e9fc2132708ae03cd23ca39b  (keybinds: use the triggering keyboard for repeat timings (11309)).
Date: Tue Aug 5 15:54:55 2025
Tag: v0.50.0-68-g2859f1b7, commits: 6347
built against:
aquamarine 0.9.2
hyprlang 0.6.3
hyprutils 0.8.2
hyprcursor 0.1.13
hyprgraphics 0.1.5
no flags were set
System Information:
System name: Linux
Node name: desktop
Release: 6.15.8-200.fc42.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Thu …
```
=> core: monitor replug workaround for nvidia

src/core/LockSurface.cpp
They are already part of the generated protocol code.
Generated dtor for wl lock surface for example:
```cpp
CCExtSessionLockSurfaceV1::~CCExtSessionLockSurfaceV1() {
if (!destroyed)
sendDestroy();
}
```
=> lock-surface: remove redundant sendDestroy calls

src/core/hyprlock.cpp, src/renderer/Renderer.cpp, src/renderer/Renderer.hpp
I set the opacity manually in my original workaround and then removed it without thinking.
This makes the workaround function as intended.
See https://github.com/hyprwm/hyprlock/pull/845
=> renderer: fix nvidia workaround
